/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ar.unsl.qualisys.paneles;


import ar.unsl.qualisys.componentes.nodos.QsOperador;
import ar.unsl.qualisys.controllers.PanelEvaluacionController;
import ar.unsl.qualisys.frames.QsFrame;
import ar.unsl.qualisys.paneles.grafo.QsDadPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author luciano.gurruchaga
 */
public class QsEvaluacionPanel extends JPanel implements EvaluacionView{
    //Swing

    //MoreSwing
    private QsFrame parent;
    private QsDadPanel DAD;

    //PanelUse
    private boolean init;
    PanelEvaluacionController evaluacionController;
    
    
    /**
     * Creates new form ValorInstancias
     */
    public QsEvaluacionPanel(QsFrame parent, PanelEvaluacionController control) {
        this.parent=parent;
        this.init = true;
        this.evaluacionController = control;
        this.evaluacionController.setVista(this);
        //Swing
        initComponents();
        this.setBackground(Color.decode("#D6CE93"));
        this.jPanel0.setBackground(Color.decode("#EFEBCE"));
        this.jPanel0.setBorder(BorderFactory.createLineBorder(Color.decode("#A3A380")));
        this.jPanel3.setBackground(Color.decode("#EFEBCE"));
        this.jPanel3.setBorder(BorderFactory.createLineBorder(Color.decode("#A3A380")));
        //Styling
        this.stylingComponent(jButtonCreate);        
        this.stylingComponent(jButtonElim);        
        this.stylingComponent(jButtonModif);        
        this.stylingComponent(jButtonResults);        
        //Qualisys
//        this.listaVariables = new ArrayList<>();// Se settea desp
//        this.instancias = new ArrayList<>();// Se settea desp
//        this.variables = new HashMap<>(); // Se settea desp 
//        this.operadores = new HashMap<>();// Se settea desp
//        this.relPadreHijos = new HashMap<>();// Se settea desp
        //PanelUse
        evaluacionController.initTablaInstancias(jPanel1);
        evaluacionController.initTablaResultados(jPanel4);
        evaluacionController.initTableResultadosParciales(jPanel5);
        this.setVisible(true);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        System.out.println("Paint");
        super.paintComponent(g);
        if(this.init){
            evaluacionController.initInstancias(); // inicializa si es que existen
        }
             
        init = false; 
    }
    
    public void setInit(boolean init) {
        this.init = init;
    }    
    
    private void stylingComponent(JComponent b){
        b.setBackground(Color.decode("#D6CE93"));
//       b.setForeground(Color.decode("#BB8588"));
        b.setBorder(BorderFactory.createLineBorder(Color.decode("#A3A380"),1,true));
        b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    } 
    
    public QsDadPanel getDAD() {
        return DAD;
    }

    public void setDAD(QsDadPanel DAD) {
        this.DAD = DAD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel0 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCreate = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonModif = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonElim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonResults = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 1200));

        jPanel0.setBackground(Color.decode("#EFEBCE"));
        jPanel0.setLayout(null);

        jLabel1.setText("Agregue las instancias que desee.");
        jPanel0.add(jLabel1);
        jLabel1.setBounds(540, 0, 463, 17);

        jButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/create-25.png"))); // NOI18N
        jButtonCreate.setText("Crear Instancia");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        jPanel0.add(jButtonCreate);
        jButtonCreate.setBounds(540, 30, 170, 29);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel0.add(jTextField1);
        jTextField1.setBounds(180, 30, 350, 29);

        jButtonModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-25.png"))); // NOI18N
        jButtonModif.setText("Modificar Instancia");
        jButtonModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifActionPerformed(evt);
            }
        });
        jPanel0.add(jButtonModif);
        jButtonModif.setBounds(720, 30, 170, 30);

        jSeparator1.setBackground(Color.decode("#EFEBCE"));
        jSeparator1.setForeground(Color.decode("#A3A380"));
        jPanel0.add(jSeparator1);
        jSeparator1.setBounds(10, 80, 520, 10);

        jButtonElim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-24.png"))); // NOI18N
        jButtonElim.setText("Eliminar Instancia");
        jButtonElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElimActionPerformed(evt);
            }
        });
        jPanel0.add(jButtonElim);
        jButtonElim.setBounds(900, 30, 170, 30);

        jLabel2.setText("Nombre de la Instancia");
        jPanel0.add(jLabel2);
        jLabel2.setBounds(12, 32, 457, 20);

        jLabel4.setText("Una vez seleccionada puede modificar o eliminar una instancia.");
        jPanel0.add(jLabel4);
        jLabel4.setBounds(540, 80, 520, 17);

        jLabel3.setText("Asigne valores a sus instancias.");
        jPanel0.add(jLabel3);
        jLabel3.setBounds(10, 100, 270, 17);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        jLabel5.setText("Evalúe sus resultados.");

        jButtonResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show-25.png"))); // NOI18N
        jButtonResults.setText("Ver Resultados");
        jButtonResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultsActionPerformed(evt);
            }
        });

        jLabel9.setText("Debe haber al menos un Modelo a evaluar. Revise sus variables.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonResults, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel9))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        evaluacionController.crearInstancia(jTextField1.getText());
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElimActionPerformed
        evaluacionController.eliminarInstancia();
    }//GEN-LAST:event_jButtonElimActionPerformed

    private void jButtonModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifActionPerformed
        evaluacionController.modificarInstancia(jTextField1.getText());
    }//GEN-LAST:event_jButtonModifActionPerformed

    private void jButtonResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultsActionPerformed
        evaluacionController.evaluarResultados();
    }//GEN-LAST:event_jButtonResultsActionPerformed

    @Override
    public void repintar() {
        this.repaint();
    }

    @Override
    public void mostrarError(String motivo) {
        JOptionPane.showMessageDialog(this, motivo);
    }

    @Override
    public void crearDialog(JTable table,QsOperador op){
        JDialog dialog = new JDialog(this.parent,"",Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setLayout(new BorderLayout());
        Container contenedor = DAD.getParent();
        JScrollPane jScrollPane4 = new JScrollPane(DAD);
        DAD.getController().setNodoSeleccionado(op);
        int x = op.getLocation().x; // coordenada x deseada
        int y = op.getLocation().y; // coordenada y deseada// Ajustar la posición de desplazamiento del JScrollPane para que la posición deseada esté centrada en la vista
        jScrollPane4.getViewport().setViewPosition(new Point(x-100, y ));       // ajusto el foco del scroll
        JScrollPane sp = new JScrollPane(table);
        sp.getViewport().setBackground(Color.decode("#EFEBCE"));
        dialog.add(sp, BorderLayout.WEST);  
        dialog.add(jScrollPane4, BorderLayout.CENTER);  
        
        dialog.setTitle("Retorno del nodo = " + op.getValorResultado() );
        dialog.setSize(800, 600); // Establecer tamaño
        dialog.setLocationRelativeTo(null); // Centrar en la pantalla
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE); // Cerrar al hacer clic en la cruz
        dialog.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                op.setBackground(Color.WHITE);
                evaluacionController.setEditableNodos(true);
                contenedor.remove(DAD); // Remove panel from its original container
                contenedor.add(DAD); // Add panel to the new container
                contenedor.revalidate(); // Revalidate the new container to reflect changes
                contenedor.repaint();
            }

            public void windowOpened(WindowEvent e) {
                evaluacionController.setEditableNodos(false);
                op.setBackground(Color.decode("#D8A48F"));
            }
        });
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonElim;
    private javax.swing.JButton jButtonModif;
    private javax.swing.JButton jButtonResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
